version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5450:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  swagger:
    build: .
    image: stock-scraper:latest
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "
      export PATH=$PATH:/root/.local/bin &&
      ./wait-for-it.sh db:5432 -- 
      ./bin/task install-dependencies &&
      poetry run alembic upgrade head &&
      poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data:

